services:
  php:
    image: lara-php:8.4
    container_name: laraphp
    restart: always
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html/
    networks:
      - app_network
    ports:
      - "8000:80"

  db:
    image: lara-mysql:9.4
    container_name: laradb
    restart: always
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: noPassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app_network

  phpmyadmin:
    platform: linux/arm64/v8
    image: phpmyadmin:5.2
    container_name: larapma
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: noPassword
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - app_network

  mailpit:
    image: axllent/mailpit
    container_name: lara-mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db-data:

networks:
  app_network:
